### ISSUE TITLE
参考サイト

### ISSUE THREAD

**Issue by kenzo-tanaka** [kenzo-tanaka/nextJsBlog#60]
https://paulintrognon.fr/
https://yossiee.com/about
https://blog.microcms.io/next-pagination/

**Comment by kenzoukenzou** [comment]
design
https://ellismin.com/

**Comment by kenzoukenzou** [comment]
[TailwindCSS で モバイル縦画面表示時のみ消える要素を作る](https://zenn.dev/junki555/articles/45614f64695b77a2ae78)

**Comment by kenzo-tanaka** [comment]
[職務経歴書](https://d0ne1s.com/career)
